require 'sinatra'
require 'sinatra/reloader'
require 'pry'
require 'active_record'
require 'sinatra/activerecord'
require 'json'
require 'pg'
require 'instagram'
require 'httparty'
require_relative 'models/blog'
require_relative 'models/cse'
require_relative 'models/user'
require_relative 'routes/insta_oath'
require_relative 'routes/login'
require_relative 'routes/register'
require_relative 'routes/select_blogs'
require_relative 'routes/search'

binding.pry

