source "https://rubygems.org"
gem 'sinatra'
gem 'sinatra-contrib'
gem 'pry'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'pg'
gem 'rake'
gem 'bcrypt'
gem 'instagram'
gem "google_custom_search_api"
